# Generated by Django 6.0.5 on 2026-06-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_comment_body_alter_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='posted_by',
            field=models.CharField(default='ghazal', max_length=100),
            preserve_default=False,
        ),
    ]
